### ISSUE TITLE
attempt to call global 'trim' (a nil value)

### ISSUE THREAD

**Issue by uloco** [kiyoon/telescope-insert-path.nvim#3]
I get the following error in the latest commit:

```
Error detected while processing /Users/uloco/.dotfiles/nvim/.config/nvim/after/plugin/telescope.rc.lua:
E5113: Error while calling lua chunk: ...cope-insert-path.nvim/lua/telescope_insert_path/init.lua:29: attempt to call global 'trim' (a nil value)
stack traceback:
        ...cope-insert-path.nvim/lua/telescope_insert_path/init.lua:29: in function 'get_git_root'
        ...cope-insert-path.nvim/lua/telescope_insert_path/init.lua:38: in function 'get_git_root_or_cwd'
        ...cope-insert-path.nvim/lua/telescope_insert_path/init.lua:268: in main chunk
        [C]: in function 'require'
        ...dotfiles/nvim/.config/nvim/after/plugin/telescope.rc.lua:14: in main chunk
```

**Comment by kiyoon** [comment]
@NoeMurr I think it should be `vim.fn.trim` right?

**Comment by NoeMurr** [comment]
I just checked, I didn't realised that I had a trim function implemented in my test environment, that's why I didn't catch it.

The vim.fn.trim method should work just fine.

If you want I can fix it later today or you can make yourself.

**Comment by kiyoon** [comment]
Thanks for the quick reply.

I'm not in the environment to test it right now, but I can modify it directly on github. Hope it fixes it.
@uloco Can you test the last commit?

**Comment by NoeMurr** [comment]
Yes I should be able to test it

**Comment by uloco** [comment]
It works, thank you :)

**Comment by kiyoon** [comment]
Thanks for reporting the issue!
