### ISSUE TITLE
Standalone picker?

### ISSUE THREAD

**Issue by hinell** [kiyoon/telescope-insert-path.nvim#5]
Why not to create standalone pickers with different commands?:

```
:Telescope insert-path-rel <arg>
:Telescope insert-path-abs <arg> 
:Telescope insert-path-rel-buf <arg>
...

```

**Comment by kiyoon** [comment]
Hi, I guess that Telescope supports already many ways to pick files - by live grep, git files, normal files etc. So it makes more sense to keep the functionality and just create a way to put the file path in the buffer.
