### ISSUE TITLE
load as extension

### ISSUE THREAD

**Issue by qrockz** [kiyoon/telescope-insert-path.nvim#7]
Hi,

how can I **register** and load your nice extension with **load_extension** ?

**Comment by kiyoon** [comment]
It doesn't really behave like an extension of Telescope, but rather it provides nice action functions you can easily map to Telescope.

**Comment by qrockz** [comment]
> It doesn't really behave like an extension of Telescope, but rather it provides nice action functions you can easily map to Telescope.

I know, but is it possible to register it as extension? 

Like:
```	
local path_actions = require("telescope_insert_path")
	require("telescope").setup({
		extensions = {
			mappings = {
				n = {
					["["] = path_actions.insert_reltobufpath_visual,
				},
			},
		},
	})
```

`require('telescope').load_extension 'telescope_insert_path'`

something like this?
I'm just curios.

**Comment by kiyoon** [comment]
Maybe it can if you change the structure of the directory and follow extension-like codes. It's been a long time since I read about it and I forgot how it works
